@url = http://localhost:5001
@deliveryId = c814d77b-fd37-41eb-a42f-086ceccf92a4
@parcels =  ['00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000']

###
GET {{url}}/deliveries/{{deliveryId}}

###
POST {{url}}/deliveries
Content-Type: application/json

{
  "parcels": {{parcels}}
}

###
POST {{url}}/deliveries/{{deliveryId}}/complete
Content-Type: application/json

{
  "deliveryId": "{{deliveryId}}"
}

###
POST {{url}}/deliveries/{{deliveryId}}/fail
Content-Type: application/json

{
  "deliveryId": "{{deliveryId}}",
  "reason": "Lost parcels."
}