@url = http://localhost:5001
@deliveryId = b064cdcd-5119-4674-a599-8d392c4aec62
@parcels =  ['1bb974b4-bf17-4d9a-a0e5-babdda41bc21']

###
GET {{url}}/deliveries/{{deliveryId}}

###
POST {{url}}/deliveries
Content-Type: application/json

{
  "parcels": {{parcels}}
}

###
POST {{url}}/deliveries/{{deliveryId}}/complete
Content-Type: application/json

{
  "deliveryId": "{{deliveryId}}"
}

###
POST {{url}}/deliveries/{{deliveryId}}/fail
Content-Type: application/json

{
  "deliveryId": "{{deliveryId}}",
  "reason": "Lost parcels."
}